import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Slab } from 'next/font/google'

const rSlab = Roboto_Slab({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Keegan's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rSlab.className}>
        nav here
        {children}
        </body>
    </html>
  )
}
